version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    environment:
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    depends_on:
      fullstack-mysql:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - fullstack

  fullstack-mysql:
    image: mysql
    container_name: full_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - fullstack-mysql
    environment:
     - PMA_HOST=fullstack-mysql
     - PMA_USER=${DB_USER}
     - PMA_PORT=${DB_PORT}
     - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack
  
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    expose:
      - 5672
    ports:
      #- 5672:5672 # for sender and consumer
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - dev_rabbitmq-data/:/var/lib/rabbitmq
      - dev_rabbitmq-log/:/var/log/rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - fullstack

  notification-app:
    container_name: notification-app
    ports:
      - 3000:3000
    build:
      context: ./notification
      dockerfile: Dockerfile.notification
    environment:
      - AMQP_SERVER_URL=amqp://guest:guest@message-broker:5672/
    restart: always
    networks:
      - fullstack
    depends_on:
      message-broker:
        condition: service_healthy

volumes:
  api:
  database_mysql:
  dev_rabbitmq-data:
  dev_rabbitmq-log:

networks:
  fullstack:
    driver: bridge